controller:
  JCasC:
    enabled: true
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: jenkins-admin
          name: "Jenkins Admin"
          password: admin-password
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
  serviceType: LoadBalancer
  servicePort: 80
  targetPort: 8080
persistence:
  storageClass: jenkins-disk-csi
  size: "100Gi"