# PostgreSQL Database Service
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: webapp
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432