apiVersion: v1
kind: ConfigMap
metadata:
  name: envars-demo
  namespace: webapp
data:
  IP_ADRESS: '*'
# Database
  POSTGRES_HOST: 'db'
  POSTGRES_PORT: '5432'
  POSTGRES_NAME: 'postgres'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgresql'
  POSTGRES_DB: 'postgres'
