apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: webapp
type: Opaque
stringData:
# Database
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgresql'
  POSTGRES_DB: 'postgres'