apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: webapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-app